# Generated by Django 4.2.11 on 2024-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QR-код'),
        ),
    ]
