# Generated by Django 4.2.11 on 2024-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='order',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR-код'),
        ),
    ]
