# Generated by Django 4.2.11 on 2024-05-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_qr_code_order_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_on_get',
        ),
    ]
